FROM node:15-alpine
#USER node

#RUN mkdir -p /home/node/app
WORKDIR '/app'

COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/build /usr/share/nginx/html